trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Snyk
  displayName: Snyk
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: SnykSecurityScan@0
    displayName: Snyk CICD scan (no reachable vuln analysis)
    inputs:
      serviceConnectionEndpoint: 'Snyk (ASM)'
      testType: 'app'
      monitorOnBuild: true
      failOnIssues: false
      projectName: 'ASMSecOpsPipline/WebGoat_2.0_clone2'
      organization: 'b24da5d1-9780-42dc-9f98-ee5427018f57'
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'Snyk (ASM)'
      testType: 'blahblahblah'
      monitorWhen: 'blahblahblah'
      failOnIssues: blahblahblah
      projectName: 'blahblahblah'
      organization: 'blahblahblah'
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'Snyk (ASM)'
      testType: 'container'
      dockerImageName: 'test'
      monitorWhen: 'always'
      failOnIssues: false
      projectName: 'ASMSecOpsPipline/WebGoat_2.0_clone2'
      organization: 'b24da5d1-9780-42dc-9f98-ee5427018f57'